## ======================================================================
## resources
## ======================================================================

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource
    tag: v0.23.0
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: gpdb_pr
  type: pull-request
  source:
    repository: greenplum-db/gpdb
    base_branch: "main"
    access_token: ((gpdb-git-access-token))
    disable_forks: true
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: gpdb7-rocky8-build
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb7-rocky8-build
    tag: latest

- name: gpdb7-rocky8-test
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb7-rocky8-test
    tag: latest

jobs:
- name: compile_and_test_gpdb
  public: true
  max_in_flight: 10
  plan:
  - in_parallel:
    - get: gpdb_pr
      trigger: true
      version: every
      params:
        submodules: true
        fetch_tags: true
    - get: gpdb7-rocky8-build
    - get: gpdb7-rocky8-test

  - put: report_pr_pending
    resource: gpdb_pr
    params:
      base_context: compile_and_test_gpdb
      path: gpdb_pr
      status: pending
    get_params:
      skip_download: true
  - # "do" the remaining steps with these hooks:
    on_failure:
      put: report_pr_failure
      resource: gpdb_pr
      params:
        base_context: compile_and_test_gpdb
        path: gpdb_pr
        status: failure
    on_success:
      put: report_pr_success
      resource: gpdb_pr
      params:
        base_context: compile_and_test_gpdb
        path: gpdb_pr
        status: success
    do:
    - in_parallel:
      - task: check_format
        file: gpdb_pr/concourse/tasks/check_format.yml
        input_mapping:
          gpdb_src: gpdb_pr

      - task: clang_tidy
        file: gpdb_pr/concourse/tasks/clang_tidy.yml
        input_mapping:
          gpdb_src: gpdb_pr

    - task: compile_gpdb_rocky8
      file: gpdb_pr/concourse/tasks/compile_gpdb.yml
      input_mapping:
        gpdb_src: gpdb_pr
      image: gpdb7-rocky8-build
      params:
        CONFIGURE_FLAGS: "--enable-cassert --enable-tap-tests --enable-debug-extensions"
        BLD_TARGETS: "clients loaders"
      timeout: 30m

    - in_parallel:
      - task: icw_planner_rocky8
        tags: [icw-worker]
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: gpdb7-rocky8-test
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
          TEST_OS: centos
          CONFIGURE_FLAGS: "--enable-cassert --enable-tap-tests"
        timeout: 3h

      - task: icw_gporca_rocky8
        tags: [icw-worker]
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: gpdb7-rocky8-test
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=on' installcheck-world
          TEST_OS: centos
          CONFIGURE_FLAGS: "--enable-cassert --enable-tap-tests"
        timeout: 5h

      - task: unit_tests_gporca_rocky8
        file: gpdb_pr/concourse/tasks/unit_tests_gporca.yml
        image: gpdb7-rocky8-build
        input_mapping:
          gpdb_src: gpdb_pr
        timeout: 1h

- name: compile_and_test_gpdb_without_assert
  public: true
  max_in_flight: 10
  plan:
  - in_parallel:
    - get: gpdb_pr
      trigger: true
      version: every
      params:
        submodules: true
        fetch_tags: true
    - get: gpdb7-rocky8-build
    - get: gpdb7-rocky8-test

  - put: report_pr_pending
    resource: gpdb_pr
    params:
      base_context: compile_and_test_gpdb_without_assert
      path: gpdb_pr
      status: pending
    get_params:
      skip_download: true
  - # "do" the remaining steps with these hooks:
    on_failure:
      put: report_pr_failure
      resource: gpdb_pr
      params:
        base_context: compile_and_test_gpdb_without_assert
        path: gpdb_pr
        status: failure
    on_success:
      put: report_pr_success
      resource: gpdb_pr
      params:
        base_context: compile_and_test_gpdb_without_assert
        path: gpdb_pr
        status: success
    do:
    - task: compile_gpdb_rocky8
      file: gpdb_pr/concourse/tasks/compile_gpdb.yml
      image: gpdb7-rocky8-build
      input_mapping:
        gpdb_src: gpdb_pr
      params:
        CONFIGURE_FLAGS: "--disable-cassert --enable-tap-tests --enable-debug-extensions"
        BLD_TARGETS: "clients loaders"
      timeout: 30m

    - in_parallel:
      - task: icw_planner_rocky8
        tags: [icw-worker]
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: gpdb7-rocky8-test
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
          TEST_OS: centos
          CONFIGURE_FLAGS: "--disable-cassert --enable-tap-tests"
        timeout: 3h

      - task: icw_gporca_rocky8
        tags: [icw-worker]
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: gpdb7-rocky8-test
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=on' installcheck-world
          TEST_OS: centos
          CONFIGURE_FLAGS: "--disable-cassert --enable-tap-tests"
        timeout: 5h

